# https://buildpacks.io/docs/reference/config/builder-config/
[[buildpacks]]
  id = "chuxel/devcontainer-features"
  uri = "docker://ghcr.io/chuxel/devcontainer-features/buildpack:v0.0.23"

[[buildpacks]]
  id = "chuxel/devcontainer-features/prodpacks/npm"
  uri = "../../prodpacks/npm"


[[order]]
    [[order.group]]
    id = "chuxel/devcontainer-features"
    optional = true

    [[order.group]]
    id = "chuxel/devcontainer-features/prodpacks/npm"

[stack]
id = "com.chuxel.stacks.test.bionic"
run-image = "ghcr.io/chuxel/devcontainer-features/stack-run-image"
build-image = "ghcr.io/chuxel/devcontainer-features/stack-build-image"