# https://buildpacks.io/docs/reference/config/builder-config/
[[buildpacks]]
  id = "${publisher}/${featureset}"
  uri = "docker://ghcr.io/${publisher}/${featureset}/devpack:${version}"

[[buildpacks]]
  id = "${publisher}/${featureset}/prodpacks/npm"
  uri = "${toml_dir}/../../prodpacks/npm"

[[order]]

    [[order.group]]
    id = "${publisher}/${featureset}"
    optional = true

    [[order.group]]
    id = "${publisher}/${featureset}/prodpacks/npm"

[stack]
id = "com.chuxel.stacks.test.bionic"
run-image = "ghcr.io/${publisher}/${featureset}/stack-run-image"
build-image = "ghcr.io/${publisher}/${featureset}/stack-build-image"