[[buildpacks]]
  id = "chuxel/devcontainer-features/mode/devcontainer"
  uri = "../../modepacks/devcontainer"

[[order]]

    [[order.group]]
      id = "chuxel/devcontainer-features/mode/devcontainer"

[stack]
  id = "com.chuxel.stacks.test.bionic"
  run-image = "ghcr.io/chuxel/devcontainer-features/stack-devcontainer-run-image"
  build-image = "ghcr.io/chuxel/devcontainer-features/stack-devcontainer-build-image"
