# Buildpack API version
api = "0.7"

# Buildpack ID and metadata
[buildpack]
  id = "chuxel/devcontainer-features/prodpacks/npm"
  version = "v0.0.1"

# Stacks that the buildpack will work with
[[stacks]]
  id = "com.chuxel.stacks.test.bionic"